- src/ReactDatePicker.js
Added Validation - Date Input Field Will accept only the numbers and ForwardSlash only.(0-9 and / )
> Added Validation - Date Input Field Will accept only the numbers and ForwardSlash only

- src/table/columnHeadersFactory.js
- src/table/index.js
- src/table/tableConfFactory.js
Added Configuration for Column Alignment , Numbers and dates will be right aligned
> Added Configuration for Column Alignment

- playground/app/simpleTable/index.js
- src/table/columnHeadersFactory.js
Apply the Custom function on the column formatting, passing function as string in the UISchema.
> EN-28 - Apply the Custom Function On the Column Formatting

- playground/app/medications/index.js
- playground/app/medications/schema.js
- playground/app/medications/uiSchema.js
- src/table/actionHeaderFactory.js
- src/table/columnHeadersFactory.js
-added functionality to soft delete on the BoostrapTable.
-added column filter to list only the active records(isSelected = true) , applied filter on "isSelected" column  and hide the column from the table.
-added new action called "UPDATE" in React bootstrap Table, for that added schema inside the "rightActions" control of bootstrap table. here : -"actionConfiguration : {fieldToUpdate} " will have the field list to update on "UPDATE" action.
> EN-192 - Added Update action in the React BoostrapTable

- playground/app/medications/uiSchema.js
- src/ReactDatePicker.js
- src/table/columnHeadersFactory.js
- added functionality to add the default date(current date) for the date column  while adding new row t the table.
- added functionality to show tooltip for the column.
> EN-166 added the new date while adding new row and added tooltip

- playground/app/medications/index.js
- playground/app/medications/schema.js
- playground/app/medications/uiSchema.js
- playground/style.css
- src/ReactDatePicker.js
- src/table/actionHeaderFactory.js
- src/table/columnHeadersFactory.js
- src/table/index.js
- src/table/tableConfFactory.js
- instead of deleting(removing) the row from the grid , we can maintain the the deleted records in the same grid with highlighted(red, added trash icon).
- after updating the column of row, added the styles to the all column values to strikeout(text-decoration : line-through;).
- implemented the functionality to revert deleted operation on row as well(updaing the column).
- modified logic to update the filter column value on the action delete.
> EN-192 After user clicks on x mark the row should get removed from grid

- README.md
* Add how to load only one or more fields & demos
* Related to #67
> Add only load one or more fields in README

- playground/app/react-date-picker/index.js
- src/ReactDatePicker.js
we have added Year and month dropdown added for datePicker
> Month and Year Dropdown added for DatePicker

- playground/app/simpleTable/index.js
- src/table/index.js
- src/table/tableConfFactory.js
added function called "handleRowSelect" on row select, will update the field-value based on the select.
field-value passed from the Uischema of the table
> Adding Row Select option into the table

- src/table/columnHeadersFactory.js
Previous format string was only writing 12-hour time
> Fix to write timestamp in 24-hour time

- playground/app/rte/index.js
- src/DraftRte.js
- src/helpers/shortkey/suggestion/index.js
- src/modified-draft-rte.js
> AutoComplete on RTE

- package-lock.json
- package.json
- playground/app/index.js
- playground/style.css
- src/helpers/shortkey/suggestion/index.js
- src/modified-draft-rte.js
This fixes some of the issues where the shortkey would render inside of the text in the RTE.
There also have been CSS changes to make the dropdown component look nicer for the shortkeys.
> Fixes issues with Shortkeys + CSS Additions

- src/DraftRte.js
- src/helpers/shortkey/addMention.js
- src/helpers/shortkey/suggestion/index.js
- src/modified-draft-rte.js
This adds support for placeholder items inside of shortkeys.
> Added support for placeholders inside of shortkeys

- playground/app/medications/uiSchema.js
- src/table/columnHeadersFactory.js
Custom-Cell-Edit html input for Quantity field
-  new Component (**CustomCellEditor**)added .
-  here,  CustomCellEditor will generate  number input as the Quantity field with general actions (change and blur).
-  number field will have the restriction to enter digits after decimal and maxlength too.
-  all operation will be performed based on the uischema we pass.
> Custom-Cell-Edit html input for Quantity field

- playground/app/procedureCodes/index.js
- playground/app/procedureCodes/uiSchema.json
- src/table/index.js
- src/table/tableConfFactory.js
Created Expandable row for table component. We have added **isTableExpandable** in table object in uischema to display Expandable row
> Added Expandable Row for table component

- playground/app/procedureCodes/index.js
- playground/app/procedureCodes/schema.json
- playground/app/procedureCodes/uiSchema.json
- src/ReactDatePicker.js
- src/table/index.js
- Updated the **ExpandableRow** component to display dynamic data in the expanded row based on the field **includeInExpandedRow**.- (Procedure Code Modifiers and advanced details).
- Updated **DatePickerComponent**  to handling the **datepicker's** _month/year_ change from the popup.
> Updated the ExpandRow component to display dynamic data based on the field "includeInExpandedRow"

- playground/app/dx/uiSchema.js
- playground/app/procedureCodes/uiSchema.json
- src/table/actionHeaderFactory.js
Dynamic window function configured in Uischema Dropdown action
> SS-4445 : Call window function , fucntionname configured in UiSchema

- package.json
> Package version updated

- package.json
- src/CollapsibleField.js
Update Collapsible component to handle receive field's form data and formcontext.
> ED-6428 : Update Collapsible component to receive field's formData

- src/table/index.js
Optionally render `question` or `answer` of `fieldData` if code and description are undefined
> ED-8481: support question/answer fields in expanded list items
